import AsideBar from "@/components/AsideBar/AsideBar";
import MainLayout from "@/components/MainLayout/MainLayout";
import "./globals.css";

export const metadata = {
  title: "NextFootball",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-gray-300 dark:bg-black">
      <body>
        <MainLayout />
        <div className="mt-20 md:ml-64 p-4">{children}</div>
      </body>
    </html>
  );
}
