import MainLayout from "@/components/MainLayout/MainLayout";
import "./globals.css";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "NextFootball",
  description: "Generated by create next app",
};
const poppins = Poppins({
  weight: ["300", "400", "500"],
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${poppins.className} bg-gray-300 dark:bg-black`}
    >
      <body>
        <MainLayout />
        <div className="mt-20 lg:ml-64 p-4">{children}</div>
      </body>
    </html>
  );
}
